package com.bulbulustur.android.businesslayer.Core.Model.UpdateModels

data class BuyerRequestUpdateModel(
    val BuyerRequestId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val BuyerRequestKey: String = "",
    val MemberName: String = "",
    val ProductName: String = "",
    val ProductDescription: String = "",
    val CategoryId: Int = 0,
    val CategoryName: String = "",
    val TradeTermId: Int = 0,
    val TradeTermName: String = "",
    val PurchaseQuantity: Double = 0.0,
    val UnitId: Int = 0,
    val UnitName: String = "",
    val UnitPrice: Double = 0.0,
    val ColorId: Int = 0,
    val ColorName: String = "",
    val MaterialTypeId: Int = 0,
    val MaterialTypeName: String = "",
    val CurrencyId: Int = 0,
    val CurrencyName: String = "",
    val CurrencySymbol: String = "",
    val ShippingTypeId: Int = 0,
    val ShippingTypeName: String = "",
    val PaymentTermId: Int = 0,
    val PaymentTermName: String = "",
    val ShippingTarget: String = "",
    val LastRequestDate: String = "",
    val MaxbudgetId: Int = 0,
    val MaxbudgetName: String = ""
)
