package com.bulbulustur.android.businesslayer.Core.Model.UpdateModels

data class OrderUpdateModel(
    val OrderId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val OrderKey: String = "",
    val OrderStatusId: Int = 0,
    val PaymentTypeId: Int = 0,
    val InvoiceTypeId: Int = 0,
    val InvoiceCountryId: Int = 0,
    val InvoiceCountryStateId: Int = 0,
    val InvoiceCountryDepartmentId: Int? = null,
    val InvoiceCityId: Int = 0,
    val InvoiceDistrictId: Int? = null,
    val InvoiceDistrict: String = "",
    val InvoicePostalCode: String = "",
    val InvoiceAddress: String = "",
    val DeliveryCountryId: Int = 0,
    val DeliveryCountryStateId: Int = 0,
    val DeliveryCountryDepartmentId: Int? = null,
    val DeliveryCityId: Int = 0,
    val DeliveryDistrictId: Int? = null,
    val DeliveryDistrict: String = "",
    val DeliveryPostalCode: String = "",
    val DeliveryAddress: String = "",
    val GrandTotal: Double = 0.0,
    val TotalNetPrice: Double = 0.0,
    val TotalVat: Double = 0.0,
    val TotalShipping: Double = 0.0,
    val InstallmentCount: Int = 0,
    val InstallmentFee: Double = 0.0,
    val ShippingBreakdownJson: String = ""
)
