package com.bulbulustur.android.businesslayer.Core.DTO

data class MemberProfileDTO(
    val MemberProfileId: Int = 0,
    val EmployeeId: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val MemberId: Int = 0,
    val Bio: String = "",
    val Score: Int = 0,
    val IsCouple: Boolean = false,
    val Height: Int? = null,
    val Weight: Int? = null,
    val BodyTypeId: Int? = null,
    val SkinToneId: Int? = null,
    val ReligionId: Int? = null,
    val DietTypeId: Int? = null,
    val ExerciseHabitId: Int? = null,
    val AlcoholHabitId: Int? = null,
    val SmokingHabitId: Int? = null,
    val MaritalStatusId: Int? = null,
    val RelationshipTypeId: Int? = null,
    val EducationId: Int? = null,
    val ChildrenPreferenceId: Int? = null,
    val HasPiercing: Boolean? = null,
    val HasTattoo: Boolean? = null,
    val PenisSize: Int? = null,
    val BreastSize: String = "",
    val JobTitle: String = "",
    val BodyHairId: Int? = null,
    val PubicHairId: Int? = null,
    val LovesArmpitHair: Boolean? = null,
    val LovesBodyHair: Boolean? = null
)
