package com.bulbulustur.android.businesslayer.Core.DTO

data class PaymentAttemptDTO(
    val PaymentAttemptId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val MerchantOid: String = "",
    val ProviderCode: String = "",
    val LanguageId: Int = 0,
    val InvoiceAddressId: Int = 0,
    val DeliveryAddressId: Int = 0,
    val InvoiceAddressText: String = "",
    val DeliveryAddressText: String = "",
    val ExpectedGrandTotal: Double = 0.0,
    val Currency: String = "",
    val InstallmentCount: Int = 0,
    val MonthlyAmount: Double = 0.0,
    val ProviderFeeRate: Double? = null,
    val ProviderFeeTotal: Double? = null,
    val BasketSnapshot: String = "",
    val ReturnUrl: String = "",
    val FailUrl: String = "",
    val CallbackUrl: String = "",
    val UserIp: String = "",
    val UserAgent: String = "",
    val TestMode: Boolean = false,
    val PaymentTransactionId: String = "",
    val AmountPaid: Int? = null,
    val PaidCurrency: String = "",
    val FailCode: String = "",
    val FailMessage: String = "",
    val OrderKey: String = "",
    val UpdatedDate: String = "",
    val ProcessedDate: String? = null
)
