package com.bulbulustur.android.businesslayer.Core.DTO

data class ProductDTO(

    // ProductInsertModel / ProductUpdateModel alanları
    val ProductId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val ProductName: String = "",
    val Description: String = "",
    val ProductCategoryId: Int = 0,
    val BrandId: Int = 0,
    val VatRateId: Int = 0,
    val ViewCount: Int = 0,
    val SeoTitle: String = "",
    val SeoDescription: String = "",
    val Rating: Double = 0.0,
    val ReviewNumber: Int? = null,
    val TotalSales: Int = 0,
    val ValidProductVariantId: Int = 0,
    val Uuid: String? = null,
    val ProductSecureKey: String? = null,
    val UnitId: Int = 0,

    // ProductDTO extended alanları
    val CategoryName: String = "",
    val CurrencySymbol: String = "",
    val Picture: String = "",
    val StoreId: Int = 0,
    val Price: Double = 0.0,
    val Store: String = "",
    val Stock: Int = 0,
    val Breadcrumb: String = "",
    val ConfirmationType: String? = null,
    val VatRate: String? = null,
    val CurrencyId: Int = 0,
    val Color: String = "",
    val Size: String = "",
    val VariantId: Int = 0,
    val StoreRating: Double = 0.0,
    val Stockcode: String = "",
    val Barcode: String = "",
    val ShippingAddressId: Int = 0,
    val ReturnAddressId: Int = 0,
    val Desi: Int = 0,
    val CommissionRate: Int = 0,
    val ShippingDuration: Int = 0,
    val ColorId: Int = 0,
    val SizeId: Int = 0,
    val StoreBasedFeatureId: Int = 0,
    val ShippingAddress: String? = null,
    val ReturnAddress: String? = null,
    val DefaultPicture: String = "",
    val AdvertSponsoreds: List<AdvertSponsoredDTO>? = null,
    val BrandData: ProductBrandDTO? = null,
    val StoreLogo: String = "",
    val ProductVariantPriceId: Int = 0
)