package com.bulbulustur.android.businesslayer.Core.DTO

data class ReturnRequestDTO(
    val ReturnRequestId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val OrderLineId: Int = 0,
    val HaveInvoice: Int = 0,
    val HaveAccessory: Int = 0,
    val ReturnRequestReasonId: Int = 0,
    val Description: String = "",
    val ReturnRequestStatusId: Int = 0,
    val Price: Double? = null,
    val CurrencyId: Int = 0,
    val ReturnKey: String = "",
    val Pictures: List<ReturnRequestPictureDTO> = emptyList(),
    val StoreId: Int = 0,
    val ProductId: Int = 0,
    val VariantId: Int = 0,
    val ProductName: String = "",
    val StoreName: String = "",
    val Currency: String = "",
    val ProductSecureKey: String = "",
    val Size: String = "",
    val Color: String = "",
    val ReturnRequestType: String = "",
    val ReturnRequestStatus: String = "",
    val MemberId: Int = 0,
    val DefaultPicture: String = "",
    val MemberName: String = "",
    val OrderStoreLineId: Int = 0,
    val OrderKey: String = "",
    val OrderId: Int = 0,
)