package com.bulbulustur.android.businesslayer.Core.DTO

data class ReturnRequestDTO(
    val ReturnRequestId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String? = null,
    val StatusId: Int = 0,
    val OrderLineId: Int = 0,
    val HaveInvoice: Int = 0,
    val HaveAccessory: Int = 0,
    val ReturnRequestReasonId: Int = 0,
    val Description: String? = null,
    val ReturnRequestStatusId: Int = 0,
    val Price: Double? = null,
    val CurrencyId: Int = 0,
    val ReturnKey: String? = null,
    val Pictures: List<ReturnRequestPictureDTO>? = null,
    val StoreId: Int = 0,
    val ProductId: Int = 0,
    val VariantId: Int = 0,
    val ProductName: String? = null,
    val StoreName: String? = null,
    val Currency: String? = null,
    val ProductSecureKey: String? = null,
    val Size: String? = null,
    val Color: String? = null,
    val ReturnRequestType: String? = null,
    val ReturnRequestStatus: String? = null,
    val MemberId: Int = 0,
    val DefaultPicture: String? = null,
    val MemberName: String? = null,
    val OrderStoreLineId: Int = 0,
    val OrderKey: String? = null,
    val OrderId: Int = 0,
)