package com.bulbulustur.android.businesslayer.Core.DTO

data class StoreRequestDTO(
    val StoreRequestId: Int = 0,
    val InsertedBy: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val StoreRequestKey: String = "",
    val CompanyId: Int = 0,
    val Name: String = "",
    val Surname: String = "",
    val Email: String = "",
    val Tckn: String = "",
    val GsmPhone: String = "",
    val CountryId: Int = 0,
    val CountryStateId: Int = 0,
    val CityId: Int = 0,
    val DistrictId: Int? = null,
    val PostCode: String = "",
    val KepAddress: String = "",
    val TaxOffice: String = "",
    val TaxId: String = "",
    val StoreName: String = "",
    val StoreDescription: String = "",
    val StaffName: String = "",
    val StaffSurname: String = "",
    val StaffDepartment: String = "",
    val StaffPosition: String = "",
    val StoreConfirmation: Int = 0,
    val BankId: Int? = null,
    val BankIban: String = "",
    val CompanyType: String = "",
    val DistrictName: String = "",
    val CityName: String = "",
    val CountryName: String = "",
    val BankName: String = "",
    val NumberOfEmployee: String = "",
    val Banka: String = ""
)