package com.bulbulustur.android.businesslayer.Core.Model.InsertModels

data class MemberInsertModel(
    val MemberId: Int = 0,
    val InsertedDate: String = "",
    val StatusId: Int = 0,
    val Name: String = "",
    val Surname: String = "",
    val Email: String = "",
    val Password: String = "",
    val GenderId: Int = 0,
    val CountryId: Int = 0,
    val CountryStateId: Int = 0,
    val CountryDepartmentId: Int? = null,
    val CityId: Int = 0,
    val DistrictId: Int? = null,
    val Activation: Boolean? = null,
    val ActivationCode: String = "",
    val ActivationDate: String? = null,
    val BirthDate: String? = null,
    val Profession: String = "",
    val ContactPreferenceSms: Int? = null,
    val ContactPreferenceEmail: Int? = null,
    val ContactPreferencePhone: Int? = null,
    val TaxOffice: String = "",
    val TaxId: String = "",
    val Tckn: String = "",
    val Uuid: String = "",
    val Picture: String = "",
    val Cancellation: Boolean = false,
    val CancellationDate: String? = null,
    val AccountDisableReasonId: Int? = null,
    val CompanyForTax: String = "",
    val MemberTypeId: Int = 0,
    val Block: Boolean = false,
    val Disable: Boolean = false,
    val IdentificationNumber: String = "",
    val FirstLogin: Boolean = false,
    val MemberSecureKey: String = ""
)
